### ISSUE TITLE
3mux crashes when gnome-terminal maximizes

### ISSUE THREAD

**Issue by jubalh** [aaronjanse/3mux#22]
* start 3mux
* press `Ctrl+b %` to split vertically
* press `Super+Upper Arrow` to maximize gnome-terminal

Getting:

```
Error during: bad file descriptor
                                                      Tiling state: Universe[0](Workspace(HSplit[0](VSplit[1](Term[82x12], Term[82x12]*))))
                                                                                                   goroutine 15 [running]:                                    
    runtime/debug.Stack(0x547ee0, 0xc000098008, 0xc000091f28)
                                                             	/usr/lib64/go/1.12/src/runtime/debug/stack.go:24 +0x9d
                                                                              main.fatalShutdownNow(0x527d80, 0x13)
                                                                                                                   	/home/michael/.golang/src/github.com/aaronjanse/3mux/main.go:123 +0x169
                                                                      main.(*Shell).resize.func1(0xc000058300, 0xc0000a4218, 0x19, 0x28)
                                                                                                	/home/michael/.golang/src/github.com/aaronjanse/3mux/shell.go:101 +0xd3
                                                         created by main.(*Shell).resize
      	/home/michael/.golang/src/github.com/aaronjanse/3mux/shell.go:94 +0xc9


        Please submit a bug report with this stack trace to https://github.com/aaronjanse/3mux/issues
```

**Comment by aaronjanse** [comment]
I can no longer reproduce this on master. Is this still an issue?

**Comment by jubalh** [comment]
Yes.

**Comment by aaronjanse** [comment]
Resize issues are no longer fatal (https://github.com/aaronjanse/3mux/commit/f5dfdad1b66836c426e422e61d66a276bd41a68e) but I'm keeping this issue open until I can fix the underlying problem.

Better logging is tracked at https://github.com/aaronjanse/3mux/issues/39
